import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      medium: true,
      large: false,
      extra_large: false,
      category: 'Shirts',
      image: '/images/p1.jpg',
      image2: '/images/p1.jpg',
      image3: '/images/p1.jpg',
      price: 120,
      countInStockM: 10,
      countInStockL: 20,
      countInStockXL: 30,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      medium: true,
      large: false,
      extra_large: false,
      category: 'Shirts',
      image: '/images/p1.jpg',
      image2: '/images/p1.jpg',
      image3: '/images/p1.jpg',
      price: 100,
      countInStockM: 50,
      countInStockL: 40,
      countInStockXL: 60,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      medium: true,
      large: false,
      extra_large: false,
      category: 'Shirts',
      image: '/images/p1.jpg',
      image2: '/images/p1.jpg',
      image3: '/images/p1.jpg',
      price: 220,
      countInStockM: 0,
      countInStockL: 0,
      countInStockXL: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      medium: true,
      large: false,
      extra_large: false,
      category: 'Pants',
      image: '/images/p1.jpg',
      image2: '/images/p1.jpg',
      image3: '/images/p1.jpg',
      price: 78,
      countInStockM: 15,
      countInStockL: 25,
      countInStockXL: 35,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      medium: true,
      large: false,
      extra_large: false,
      category: 'Pants',
      image: '/images/p1.jpg',
      image2: '/images/p1.jpg',
      image3: '/images/p1.jpg',
      price: 65,
      countInStockM: 37,
      countInStockL: 97,
      countInStockXL: 57,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      medium: true,
      large: false,
      extra_large: false,
      category: 'Pants',
      image: '/images/p1.jpg',
      image2: '/images/p1.jpg',
      image3: '/images/p1.jpg',
      price: 139,
      countInStockM: 52,
      countInStockL: 54,
      countInStockXL: 56,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;